### ISSUE TITLE
Cannot connect using TLS

### ISSUE THREAD

**Issue by mundschenk-at** [erkexzcx/valetudopng#4]
**Describe the bug**
When trying to connect to the MQTT broker using TLS, the connection fails ```[MQTT producer] Failed to connect: network Error : EOF. Retrying in 5 seconds...```. Other clients connect over TLS on this port without problem, and a non-encrypted connection on port `1883` works for `valetudopng`.

**To Reproduce**
Relevant configuration:

```yaml
mqtt:
  connection:
    port: 8883
  tls_ca_path: /root_ca.pem
  tls_insecure:
```

The CA root certificate is mounted to the relevant path and apparently can be opened by the binary (otherwise I'd expect a different error message from looking at the Go code). Changing `tls_insecure` to to `true` did not change the resulting error message. 

**Expected behavior**
An MQTT connection can be established using a TLS listener.
